baseURL = "https://zishu.me"
title = "子舒的博客"
theme = "hugo-theme-m10c"

[pagination]
  pagerSize = 12

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "message"
    name = "Message"
    url = "/message/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  title = "zishu.me"
  author = "子舒"
  description = "无人扶我青云志，我自踏雪至山巅。一名 Web 前端开发工程师，热爱生活。"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/dlzmoe"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/dlzmoe"

  # Default theme
  # [params.style]
  #   darkestColor = "#242930"
  #   darkColor = "#353b43"
  #   lightColor = "#afbac4"
  #   lightestColor = "#ffffff"
  #   primaryColor = "#57cc8a"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff"
