name = "cloud"
license = "GPLv2"
licenselink = "https://raw.githubusercontent.com/yuanj82/cloud/main/LICENSE"
description = "Cloud is a hugo theme with a simple, classic and nostalgic style, paying tribute to the era."
homepage = "https://github.com/yuanj82/cloud"
demosite = "https://yuanj.top"
tags = ["blog", "responsive", "light","customizable", "widgets"]
features = ["blog", "responsive", "multilingual", "widgets", "rss"]

[author]
  name = "Jiao Yuan"
  homepage = "https://github.com/yuanj82"

# If porting an existing theme
[original]
  name = "Mainroad"
  homepage = "https://github.com/Vimux/Mainroad"
  repo = "https://github.com/Vimux/Mainroad"
