name: Update README with RSS Feed

on:
  push:  # 每次提交代码时触发
    branches:
      - main  # 指定触发的分支，修改为你的主分支名称

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install feedparser

      - name: Read RSS feed and update README.md
        run: |
          import feedparser
          import datetime
          import re

          # 这里替换为你的 RSS 源
          rss_url = "https://zishu.me/index.xml"
          feed = feedparser.parse(rss_url)

          # 获取最近的五篇文章
          articles = feed.entries[:5]

          # 创建 Markdown 格式的内容
          articles_md = ""
          for article in articles:
              title = article.title
              link = article.link
              pub_date = datetime.datetime(*article.published_parsed[:6]).strftime('%Y-%m-%d %H:%M:%S')
              articles_md += f"[{title}]({link}) | {pub_date}\n"

          # 读取现有 README.md 内容
          with open("README.md", "r") as f:
              readme_content = f.read()

          # 在指定位置插入新内容
          new_readme_content = re.sub(
              r'<!-- START -->.*<!-- END -->',
              f'<!-- START -->\n{articles_md}<!-- END -->',
              readme_content,
              flags=re.DOTALL
          )

          # 更新 README.md
          with open("README.md", "w") as f:
              f.write(new_readme_content)

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest articles from RSS feed" || echo "No changes to commit"
          git push
